create database APAZON;
use APAZON;
 /*VAMOS A CREAR UNA MINI BASE DE DATOS QUE GUARDE RELACION ENTRE SI SIMILAR A AMAZON*/
create table CLIENTES(
CODC INT primary KEY auto_increment,
NOMBRE CHAR(60) NOT NULL COMMENT "NOMBRE COMPLETO DEL CLIENTE", 
CODIGOPOSTAL CHAR(5) NOT NULL, 
COMENTARIOS mediumtext  /*Tipo de campo varchar pero mas grande*/
);
create table COMPRA(
CODCLI INT NOT NULL,
FECHACOMPRA TIMESTAMP DEFAULT current_timestamp,   /*se coloca la fecha actual automaticamente*/
FENTREGA DATE,
FOREIGN KEY (CODCLI) REFERENCES CLIENTES (CODC),
FOREIGN KEY (CODPRO) REFERENCES PRODUCTOS (CODP)
);
use APAZON;



