use coches;
select*from clientes;

create database paquito;
use paquito; /*voy a usar esta, use se esta utilizanddo*/

create table AMIGOS(
COD INT primary KEY auto_increment,
NOMBRE CHAR(50) NOT NULL, 
TLF CHAR(30) NOT NULL,
SEXO SET("HOMBRE","MUJER") NOT NULL,  /*se dan solo dos opciones*/
CIUDAD CHAR(50),
FECHAALTA TIMESTAMP DEFAULT current_timestamp,  /*se coloca la fecha actual automaticamente*/
COMENTARIOS mediumtext  /*Tipo de campo varchar pero mas grande*/
);
INSERT INTO AMIGOS (NOMBRE, TLF, SEXO, CIUDAD, COMENTARIOS) VALUES
 ("PERRICO","603385235", "MUJER", "BARCELONA", "ES MUY MAJO");
SELECT*FROM AMIGOS;
SELECT*FROM AMIGOS;
DELETE FROM AMIGOS WHERE COD="4";/*SE BORRA CON EL WHERE COD= al cod que quieras borrar*/
TRUNCATE AMIGOS;/*BORRA TODOS LOS DATOS DE LA TABLA PERO DEJA LA EXTRUCTURA*/
DROP TABLE AMIGOS;/*BORRAMOS LA TABLA*/
ALTER TABLE AMIGOS ADD COLUMN VALOR INTEGER AFTER NOMBRE;/*AÑADIMOS UNA COLUMNA DESPUES DE NOMBRE (INTEGER ES INT PARA VALORAR DEL 1 AL 10 POR EJEMPLO*/
DESCRIBE AMIGOS;/*TE APARECE LA TABLA CON EL TYPO DE DATO EL TAMAÑO SI ES NOT NULL O NULL LA PRIMARY KEY ETC*/

create table FAMILIA(
COD INT PRIMARY KEY auto_increment,
NOMBRE CHAR(30) NOT NULL,
APEL1 CHAR(10) NOT NULL,
APEL2 CHAR(10) NOT NULL,
FECHANACIMIENTO DATE
);
SELECT*FROM FAMILIA;
INSERT INTO FAMILIA (NOMBRE, APEL1, APEL2, FECHANACIMIENTO) VALUES
("MIRI","COLLAGUAZO", "GUANOLEMA", "1997/11/10"),
("ELI","SANS", "FERNANDEZ", "1995/11/10"),
("FER","PEREZ", "SANCHEZ", "1993/11/10"),
("MIGUEL","ALVAREZ", "LOPEZ", "1991/11/10");
DELETE FROM FAMILIA WHERE COD="2";
SELECT*FROM FAMILIA WHERE APEL1 LIKE"%Z";/* TE MUESTRA LOS NOMBRES QUE CONTENGAN Z AL FINAL DE LA PALABRA*/
SELECT*FROM FAMILIA;
SELECT CONCAT(APEL1," ", APEL2," ", NOMBRE) FROM FAMILIA; /* TE MUESTRA LOS DATOS COMO QUIERES QUE LOS MUESTRE EN EL ORDEN QUE QUIERAS*/
SELECT CONCAT(APEL1," ", APEL2," ", NOMBRE) AS NOMBRE_EMPLEADO FROM FAMILIA; /* TE MUESTRA LOS DATOS COMO QUIERES QUE LOS MUESTRE EN EL ORDEN QUE QUIERAS COLOCA EL NOMBRE EN VEZ DE LA CONCANETACION*/
SELECT CONCAT (LEFT(NOMBRE,1),"-",(APEL1,1),"-",(APEL2,1))FROM FAMILIA;

SELECT round(datediff(NOW(), FECHANACIMIENTO)/365) FROM FAMILIA; /*ROUND ES PARA REDONDEAR, DATEDIFF PARA SUMAR RETAR PO DIVIDIR*/



