CREATE DATABASE FORMACION;
USE FORMACION;

CREATE TABLE ALUMNOS(
	COD INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    APELLIDOS VARCHAR(100),
    FNACI DATE,
    NOTA1 DOUBLE,
    NOTA2 DOUBLE,
    FINAL DOUBLE,#CON EL PROCEDIMIENTO ESTA COLUMNA SE RELLENARA SOLO
    CEXP VARCHAR(15)
);

INSERT INTO ALUMNOS (NOMBRE,APELLIDOS,FNACI,NOTA1,NOTA2) VALUES 
('ANDREA','ALVAREZ','2002-12-01',5.5,9.0);
INSERT INTO ALUMNOS (NOMBRE,APELLIDOS,FNACI,NOTA1,NOTA2) VALUES 
('MIRI','COLLA','2010-09-05',7.5,6.0);
INSERT INTO ALUMNOS (NOMBRE,APELLIDOS,FNACI,NOTA1,NOTA2) VALUES 
('LUIS','BELTRE','2015-07-04',3.2,9.0);

SELECT  * FROM ALUMNOS;
SELECT  * FROM ACTAS;
CREATE TABLE ACTAS (
	CODIGO INTEGER,
    APELNOM CHAR(100),
    NOTA DOUBLE,
    CODEXP  CHAR(15)#CODIGO EXPEDIENTE ESTA COLUMNA ES LA QUE SE VA AUTORELLENAR
);

CALL EVALUADOR();