CREATE DATABASE FORMACION;
USE FORMACION;

CREATE TABLE ALUMNOS(
	COD INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    APELLIDOS VARCHAR(100),
    FNACI DATE,
    NOTA1 DOUBLE,
    NOTA2 DOUBLE,
    FINAL DOUBLE,
    CEXP VARCHAR(15)
);

INSERT INTO ALUMNOS (NOMBRE,APELLIDOS,FNACI,NOTA1,NOTA2) VALUES 
('ANDREA','ALVAREZ','2002-12-01',5.5,9.0);

SELECT  * FROM ALUMNOS;

CREATE TABLE ACTAS (
	CODIGO INTEGER,
    APELNOM CHAR(100),
    NOTA DOUBLE,
    CODEXP  CHAR(15)
);



CREATE DEFINER=`root`@`localhost` PROCEDURE `EVALUADOR`()
BEGIN
	DECLARE MEDIA DOUBLE;
    DECLARE N1 DOUBLE;
    DECLARE N2 DOUBLE;
    DECLARE CODIGOE VARCHAR(20);
    DECLARE CONTADOR INTEGER;
    DECLARE REG INTEGER;
    
    SET CONTADOR = 1;
    SET REG = (SELECT MAX(COD) FROM ALUMNOS);
    
		WHILE CONTADOR<=REG DO
        
			SET N1 = (SELECT NOTA1 FROM ALUMNOS WHERE COD=CONTADOR);
			SET N2 = (SELECT NOTA2 FROM ALUMNOS WHERE COD=CONTADOR);
            SET MEDIA = (N1+N2)/2;
            
            UPDATE ALUMNOS SET FINAL=MEDIA WHERE COD=CONTADOR;
            
            SET CODIGOE = (SELECT concat_ws('-',LEFT(NOMBRE,2),LEFT(APELLIDOS,2),YEAR(FNACI)) 
            FROM ALUMNOS WHERE COD=CONTADOR);
  
            UPDATE ALUMNOS SET CEXP=CODIGOE WHERE COD=CONTADOR;
            
            INSERT INTO ACTAS (CODIGO,APELNOM,NOTA,CODEXP) VALUES ((SELECT COD FROM ALUMNOS WHERE COD=CONTADOR),'PEPE',MEDIA,CODIGOE);
            
            SET CONTADOR = CONTADOR + 1;      
        END WHILE;
 END