CREATE DATABASE CAMPUSFP;
USE CAMPUSFP;

CREATE TABLE ALUMNOS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) NOT NULL,
APEL1 VARCHAR(20) NOT NULL,
APEL2 VARCHAR(20) NOT NULL,
FNACI DATE,
EDAD DOUBLE,
EX1 DOUBLE,
EX2 DOUBLE,
EX3 DOUBLE,
NOTA DOUBLE,
CALIFICACION VARCHAR(20)
);

CREATE TABLE ACTAS (
ID INT PRIMARY KEY AUTO_INCREMENT,
APELNOM VARCHAR(60) NOT NULL,
EVALUCION VARCHAR(20),
FECHA DATE
);

CREATE TABLE RECUPERACIONES (
ID INT PRIMARY KEY AUTO_INCREMENT,
APELLIDOSNOM VARCHAR(60) NOT NULL,
NOTA DOUBLE,
FECHA DATE
);

INSERT INTO ALUMNOS (NOMBRE,APEL1,APEL2,FNACI,EX1,EX2,EX3) VALUES 
('PEDRO','LOPEZ', 'ALVAREZ', '2001-01-01','5.5','6.70','7.5'),
('PEPE','LOPEZ', 'ALVAREZ', '2003-10-20','8.5','7.70','7.5'),
('RAMIRO','LOPEZ', 'ALVAREZ', '2001-01-01','5.5','5.70','2.5'),
('ALBERTO','LOPEZ', 'ALVAREZ', '2010-05-01','5.5','6.70','9.5'),
('LUIS','LOPEZ', 'ALVAREZ', '2006-08-01','3.5','4.70','9.5'),
('ANA','LOPEZ', 'ALVAREZ', '2003-12-01','1.5','5.70','7.5');

SELECT * FROM ALUMNOS;
SELECT * FROM ACTAS;
SELECT * FROM RECUPERACIONES;
/* 
CREATE DEFINER=`root`@`localhost` FUNCTION `NOTALETRA`(NOTA DOUBLE) RETURNS char(30) CHARSET utf8mb4 COLLATE utf8mb4_general_ci
BEGIN
	DECLARE RESULTADO CHAR(30);
    IF ((NOTA>=0) && (NOTA<=10)) THEN
		IF ((NOTA>=0) && (NOTA<4)) THEN
			SET RESULTADO = 'Deficiente';
		ELSEIF ((NOTA>=4) && (NOTA<5)) THEN
			SET RESULTADO = 'Suspenso';
		ELSEIF ((NOTA>=5) && (NOTA<6)) THEN
			SET RESULTADO = 'Sufiente';
		ELSEIF ((NOTA>=6) && (NOTA<7)) THEN
			SET RESULTADO = 'Bien';
		ELSEIF ((NOTA>=7) && (NOTA<9)) THEN
			SET RESULTADO = 'Notable';
		ELSEIF ((NOTA>=9) && (NOTA<10)) THEN
			SET RESULTADO = 'Sobresaliente';
		END IF;
    ELSE
		SET RESULTADO = 'LA NOTA INTRODUCIDA ES ERRONEA';
    END IF;
RETURN RESULTADO;
END
*/

SELECT NOTALETRA(5.5) AS RESULTADO;

UPDATE ALUMNOS SET EX1= 0.0 WHERE NOMBRE='PEDRO';
UPDATE ALUMNOS SET NOTA = 0.0;


SET SQL_SAFE_UPDATES=0;
DROP TRIGGER EVALUA;

SHOW TRIGGERS;